/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gs.form.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FormEntry service. Represents a row in the &quot;Form_FormEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.gs.form.model.impl.FormEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.gs.form.model.impl.FormEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FormEntry
 * @generated
 */
@ProviderType
public interface FormEntryModel extends BaseModel<FormEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form entry model instance should use the {@link FormEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this form entry.
	 *
	 * @return the primary key of this form entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form entry.
	 *
	 * @param primaryKey the primary key of this form entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this form entry.
	 *
	 * @return the uuid of this form entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this form entry.
	 *
	 * @param uuid the uuid of this form entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the form ID of this form entry.
	 *
	 * @return the form ID of this form entry
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this form entry.
	 *
	 * @param formId the form ID of this form entry
	 */
	public void setFormId(long formId);

	/**
	 * Returns the name of this form entry.
	 *
	 * @return the name of this form entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this form entry.
	 *
	 * @param name the name of this form entry
	 */
	public void setName(String name);

	/**
	 * Returns the last name of this form entry.
	 *
	 * @return the last name of this form entry
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this form entry.
	 *
	 * @param lastName the last name of this form entry
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the birthday of this form entry.
	 *
	 * @return the birthday of this form entry
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this form entry.
	 *
	 * @param birthday the birthday of this form entry
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the email of this form entry.
	 *
	 * @return the email of this form entry
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this form entry.
	 *
	 * @param email the email of this form entry
	 */
	public void setEmail(String email);

	/**
	 * Returns the create date of this form entry.
	 *
	 * @return the create date of this form entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this form entry.
	 *
	 * @param createDate the create date of this form entry
	 */
	public void setCreateDate(Date createDate);

}